	SELECT SUM(COUNCIL.COMPREHENSIVE_BLEND_CA.WEIGHT_POSTED) AS TONS,
        COUNCIL.COMPREHENSIVE_BLEND_CA.REPORTING_AREA_CODE,
        COUNCIL.COMPREHENSIVE_BLEND_CA.FMP_GEAR,
        COUNCIL.COMPREHENSIVE_BLEND_CA.AGENCY_GEAR_CODE,
        COUNCIL.COMPREHENSIVE_BLEND_CA.FMP_AREA,
        COUNCIL.COMPREHENSIVE_BLEND_CA.FMP_SUBAREA,
        COUNCIL.COMPREHENSIVE_BLEND_CA.YEAR AS YEAR,
        COUNCIL.COMPREHENSIVE_BLEND_CA.SPECIES_GROUP_CODE,
        COUNCIL.COMPREHENSIVE_BLEND_CA.TRIP_TARGET_CODE,
        COUNCIL.COMPREHENSIVE_BLEND_CA.AGENCY_SPECIES_CODE, 
        COUNCIL.COMPREHENSIVE_BLEND_CA.SPECIES_NAME,  
        COUNCIL.COMPREHENSIVE_BLEND_CA.VES_AKR_LENGTH,
        to_char(COUNCIL.COMPREHENSIVE_BLEND_CA.week_end_date,'mm') as MONTH
      FROM 
        COUNCIL.COMPREHENSIVE_BLEND_CA
      WHERE 
        COUNCIL.COMPREHENSIVE_BLEND_CA.YEAR > 1990 
        AND COUNCIL.COMPREHENSIVE_BLEND_CA.TRIP_TARGET_CODE 
        -- insert TRIP_TAR_CODE
        AND COUNCIL.COMPREHENSIVE_BLEND_CA.AGENCY_SPECIES_CODE
        -- insert SPECIES_GRP_CODE
            AND COUNCIL.COMPREHENSIVE_BLEND_CA.REPORTING_AREA_CODE
        -- insert AREA
      GROUP BY 
        COUNCIL.COMPREHENSIVE_BLEND_CA.REPORTING_AREA_CODE,
        COUNCIL.COMPREHENSIVE_BLEND_CA.FMP_GEAR,
        COUNCIL.COMPREHENSIVE_BLEND_CA.AGENCY_GEAR_CODE,
        COUNCIL.COMPREHENSIVE_BLEND_CA.YEAR,
        COUNCIL.COMPREHENSIVE_BLEND_CA.SPECIES_GROUP_CODE,
        COUNCIL.COMPREHENSIVE_BLEND_CA.TRIP_TARGET_CODE,
        COUNCIL.COMPREHENSIVE_BLEND_CA.AGENCY_SPECIES_CODE, 
        COUNCIL.COMPREHENSIVE_BLEND_CA.SPECIES_NAME,
        COUNCIL.COMPREHENSIVE_BLEND_CA.FMP_SUBAREA,
        COUNCIL.COMPREHENSIVE_BLEND_CA.FMP_AREA,
        COUNCIL.COMPREHENSIVE_BLEND_CA.VES_AKR_LENGTH,
        to_char(COUNCIL.COMPREHENSIVE_BLEND_CA.week_end_date,'mm')